/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(differential_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(14d417c9430f717084d1424929e47ae6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nabu/differential_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <differential_encoder_pydoc.h>

void bind_differential_encoder(py::module& m)
{

    using differential_encoder    = gr::nabu::differential_encoder;


    py::class_<differential_encoder, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<differential_encoder>>(m, "differential_encoder", D(differential_encoder))

        .def(py::init(&differential_encoder::make),
           D(differential_encoder,make)
        )
        



        ;




}








