/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(symbols_to_complex.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7189f70779f78de469da3e7f4e43ef11)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nabu/symbols_to_complex.h>
// pydoc.h is automatically generated in the build directory
#include <symbols_to_complex_pydoc.h>

void bind_symbols_to_complex(py::module& m)
{

    using symbols_to_complex    = gr::nabu::symbols_to_complex;


    py::class_<symbols_to_complex, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<symbols_to_complex>>(m, "symbols_to_complex", D(symbols_to_complex))

        .def(py::init(&symbols_to_complex::make),
           D(symbols_to_complex,make)
        )
        



        ;




}








